ADD_SCENE(tpms, start, Start)
ADD_SCENE(tpms, saved, Saved)
ADD_SCENE(tpms, settings, Settings)
ADD_SCENE(tpms, protocol_list, ProtocolList)
ADD_SCENE(tpms, protocol_test, ProtocolTest)
ADD_SCENE(tpms, about, About)
ADD_SCENE(tpms, receiver, Receiver)
ADD_SCENE(tpms, relearn_config, Relearn)
ADD_SCENE(tpms, receiver_config, ReceiverConfig)
ADD_SCENE(tpms, receiver_info, ReceiverInfo)
ADD_SCENE(tpms, editor, Editor)
ADD_SCENE(tpms, simulation, Simulation)

ADD_SCENE(tpms, lab_pin, LabPin)
ADD_SCENE(tpms, lab_pressure, LabPressure)
ADD_SCENE(tpms, lab_sensors, LabSensors)
ADD_SCENE(tpms, lab_run, LabRun)
