#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/** Reset only the in-RAM duplicate filter. The CSV on SD is intentionally persistent. */
void tpms_ford_diag_reset_session(void);

/**
 * Append one decoded Ford frame to the persistent diagnostic CSV.
 * Exact duplicate payloads are suppressed within the current receiver session.
 *
 * RxPreset is the preset used by the receiver, not a claim about the exact
 * modulation generated by the sensor.
 */
bool tpms_ford_diag_append(
    uint32_t id,
    float pressure_kpa,
    float temperature_c,
    uint32_t frequency_hz,
    uint8_t radio_preset,
    float rssi_dbm,
    uint8_t wake_profile,
    bool wake_profile_valid,
    const uint8_t* raw_payload,
    size_t raw_payload_size);
